def get_manual():
    return {'Acne': ['Non-cancer illness code, self-reported: acne/acne vulgaris'],
 'Actinic keratosis': ['Actinic keratosis'],
 'Acute myeloid leukaemia': ['Myeloid leukaemia'],
 'Agranulocytosis': ['Diagnoses - main ICD10: D70 Agranulocytosis'],
 'Amnesia': ['Memory loss'],
 'Anaemia': ['Non-cancer illness code, self-reported: anaemia'],
 'Angina pectoris': ['Diagnoses - main ICD10: I20 Angina pectoris',
  'Non-cancer illness code, self-reported: angina'],
 'Angina unstable': [
  'Unstable angina pectoris'],
 'Anxiety disorder': ['Anxiety disorders'],
 'Arrhythmia': ['Non-cancer illness code, self-reported: heart arrhythmia',
  'Non-cancer illness code, self-reported: irregular heart beat'],
 'Arteriosclerosis': ['Diagnoses - main ICD10: I70 Atherosclerosis'],
 'Arthralgia': ['Non-cancer illness code, self-reported: joint pain'],
 'Arthritis': ['Non-cancer illness code, self-reported: arthritis (nos)'],
 'Arthropathy': ['Non-cancer illness code, self-reported: other joint disorder',
  '#Arthrosis',
  'Non-cancer illness code, self-reported: joint disorder'],
 'Ascites': ['Diagnoses - main ICD10: R18 Ascites'],
 'Asthma': [
  'Non-cancer illness code, self-reported: asthma',
  'Asthma',
  'Diagnoses - main ICD10: J45 Asthma'],
 'Atrial fibrillation': ['Non-cancer illness code, self-reported: atrial fibrillation'],
 'Atrioventricular block': ['AV-block'],
 'Atrioventricular block complete': ['AV-block'],
 'Atrioventricular block first degree': ['AV-block'],
 'Atrioventricular block second degree': ['AV-block'],
 'Back pain': ['Dorsalgia',
  'Non-cancer illness code, self-reported: back pain',
  'Diagnoses - main ICD10: M54 Dorsalgia'],
 'Basal cell carcinoma': ['Cancer code, self-reported: rodent ulcer',
  'Cancer code, self-reported: basal cell carcinoma'],
 'Bone disorder': ['Non-cancer illness code, self-reported: bone disorder'],
 'Bone pain': ['Non-cancer illness code, self-reported: joint pain'],
 'Breast cancer': ['Diagnoses - main ICD10: C50 Malignant neoplasm of breast',
  'Malignant neoplasm of breast',
  'Breast Cancer'],
 'Breast enlargement': ['Diagnoses - main ICD10: N62 Hypertrophy of breast'],
 'Breast neoplasm': ['Diagnoses - main ICD10: C50 Malignant neoplasm of breast',
  'Malignant neoplasm of breast',
  'Breast Cancer'],
 'Bronchitis': ['Bronchitis',
  'Non-cancer illness code, self-reported: bronchitis'],
 'Bronchopneumonia': ['Non-cancer illness code, self-reported: pneumonia'],
 'Candida infection': ['Diagnoses - main ICD10: B37 Candidiasis'],
 'Cardiac failure': ['Heart failure',
  'Diagnoses - main ICD10: I50 Heart failure'],
 'Cardiac failure congestive': ['Heart failure'],
 'Cardiomyopathy': ['Diagnoses - main ICD10: I42 Cardiomyopathy',
  'Non-cancer illness code, self-reported: cardiomyopathy',
  'Cardiomyopathy'],
 'Carpal tunnel syndrome': ['Carpal tunnel syndrome',
  'Non-cancer illness code, self-reported: carpal tunnel syndrome'],
 'Cataract': ['Non-cancer illness code, self-reported: cataract'],
 'Cataract subcapsular': ['Non-cancer illness code, self-reported: cataract'],
 'Cellulitis': ['Diagnoses - main ICD10: L03 Cellulitis',
  'Non-cancer illness code, self-reported: cellulitis'],
 'Cerebral haemorrhage': ['Diagnoses - main ICD10: I61 Intracerebral haemorrhage'],
 'Cerebral infarction': ['Diagnoses - main ICD10: I63 Cerebral infarction'],
 'Cerebrovascular accident': ['STROKE',
  'Non-cancer illness code, self-reported: stroke',
  'Diagnoses - main ICD10: I64 Stroke, not specified as haemorrhage or infarction'],
 'Chest discomfort': ['Chest pain or discomfort'],
 'Chest pain': ['Chest pain or discomfort'],
 'Cholecystitis': ['Non-cancer illness code, self-reported: cholecystitis',
  'Diagnoses - main ICD10: K81 Cholecystitis'],
 'Cholelithiasis': ['Diagnoses - main ICD10: K80 Cholelithiasis'],
 'Colitis ulcerative': ['Ulcerative Colitis',
  'Diagnoses - main ICD10: K51 Ulcerative colitis',
  'Inflammatory Bowel Disease',
  'Non-cancer illness code, self-reported: ulcerative colitis'],
 'Conduction disorder': ['Conduction disorders'],
 'Constipation': ['Non-cancer illness code, self-reported: constipation'],
 'Coronary artery disease': ['Coronary Artery Disease'],
 'Cough': ['Diagnoses - main ICD10: R05 Cough'],
 'Cystitis': ['Diagnoses - main ICD10: N30 Cystitis',
  'Non-cancer illness code, self-reported: cystitis'],
 'Cystitis noninfective': ['Non-cancer illness code, self-reported: cystitis'],
 'Dental caries': ['Diagnoses - main ICD10: K02 Dental caries'],
 'Depressed mood': ['Non-cancer illness code, self-reported: depression',
  'Depression'],
 'Depression': ['Non-cancer illness code, self-reported: depression',
  'Depression'],
 'Dermatitis atopic': ['Eczema'],
 'Diabetes mellitus': ['Diagnoses - main ICD10: E14 Unspecified diabetes mellitus',
  'Non-cancer illness code, self-reported: diabetes'],
 'Drug abuse': ['Substance abuse'],
 'Drug dependence': ['Substance abuse'],
 'Drug eruption': ['Eczema'],
 'Dry eye': ['Non-cancer illness code, self-reported: dry eyes'],
 'Duodenal ulcer': ['Non-cancer illness code, self-reported: peptic ulcer',
  'Diagnoses - main ICD10: K26 Duodenal ulcer',
  'Non-cancer illness code, self-reported: duodenal ulcer'],
 'Dyslipidaemia': ['Non-cancer illness code, self-reported: high cholesterol'],
 'Dyspepsia': ['Diagnoses - main ICD10: K30 Dyspepsia',
  'Non-cancer illness code, self-reported: dyspepsia / indigestion'],
 'Dysphagia': ['Diagnoses - main ICD10: R13 Dysphagia'],
 'Dysuria': ['Diagnoses - main ICD10: R30 Pain associated with micturition'],
 'Eczema': [
  'Eczema'],
 'Emotional distress': ['Non-cancer illness code, self-reported: stress'],
 'Enuresis': ['Diagnoses - main ICD10: R32 Unspecified urinary incontinence'],
 'Epilepsy': ['Non-cancer illness code, self-reported: epilepsy',
  'Diagnoses - main ICD10: G40 Epilepsy'],
 'Eye infection': ['Non-cancer illness code, self-reported: eye infection'],
 'Faecal incontinence': ['Diagnoses - main ICD10: R15 Faecal incontinence'],
 'Fracture': ['Non-cancer illness code, self-reported: bone disorder'],
 'Fungal infection': ['Mycoses'],
 'Fungal skin infection': ['Mycoses'],
 'Gastric ulcer': ['Non-cancer illness code, self-reported: peptic ulcer',
  'Diagnoses - main ICD10: K25 Gastric ulcer'],
 'Gastrointestinal disorder': ['Non-cancer illness code, self-reported: stomach disorder'],
 'Gastrointestinal haemorrhage': ['GI-bleeding'],
 'Gastrooesophageal reflux disease': ['Diagnoses - main ICD10: K21 Gastro-oesophageal reflux disease'],
 'Glaucoma': ['Non-cancer illness code, self-reported: glaucoma',
  'Diagnoses - main ICD10: H40 Glaucoma'],
 'Glomerulonephritis': ['Glomerulonephritis'],
 'Glucose tolerance impaired': ['Non-cancer illness code, self-reported: diabetes'],
 'Goitre': ['Non-cancer illness code, self-reported: thyroid goitre'],
 'Gout': ['Gout, unspecified',
  'Diagnoses - main ICD10: M10 Gout',
  'Non-cancer illness code, self-reported: gout'],
 'Grand mal convulsion': ['Non-cancer illness code, self-reported: epilepsy'],
 'Gynaecomastia': ['Diagnoses - main ICD10: N62 Hypertrophy of breast'],
 'Haematuria': ['Diagnoses - main ICD10: R31 Unspecified haematuria'],
 'Haemolytic anaemia': ['Non-cancer illness code, self-reported: anaemia'],
 'Haemorrhoids': ['Diagnoses - main ICD10: I84 Haemorrhoids',
  'Non-cancer illness code, self-reported: haemorrhoids / piles'],
 'Headache': ['Diagnoses - main ICD10: R51 Headache'],
 'Heart rate irregular': ['Non-cancer illness code, self-reported: irregular heart beat'],
 'Hemiplegia': ['Diagnoses - main ICD10: G81 Hemiplegia'],
 'Hepatic cancer': ['Malignant neoplasm of liver and intrahepatic bile ducts'],
 'Hepatitis': ['Non-cancer illness code, self-reported: hepatitis'],
 'Hepatitis acute': ['Non-cancer illness code, self-reported: hepatitis'],
 'Hepatitis cholestatic': ['Non-cancer illness code, self-reported: hepatitis'],
 'Hepatitis fulminant': ['Non-cancer illness code, self-reported: hepatitis'],
 'Hepatitis toxic': ['Non-cancer illness code, self-reported: hepatitis'],
 'Hepatobiliary disease': ['Diseases of liver'],
 'Hernia': ['Hernia'],
 'Herpes zoster': ['Non-cancer illness code, self-reported: shingles'],
 'Hiatus hernia': ['Non-cancer illness code, self-reported: hiatus hernia',
  'Hernia'],
 'Hypercholesterolaemia': ['Non-cancer illness code, self-reported: high cholesterol'],
 'Hypersomnia': ['Sleeping too much'],
 'Hypertension': ['Diagnoses - main ICD10: I10 Essential (primary) hypertension',
  'Non-cancer illness code, self-reported: hypertension',
  'Hypertensive diseases',
  'Hypertension'],
 'Hypochromic anaemia': [
  'Diagnoses - main ICD10: D50 Iron deficiency anaemia'],
 'Hypotension': ['Diagnoses - main ICD10: I95 Hypotension'],
 'Ileus': ['Non-cancer illness code, self-reported: constipation'],
 'Insomnia': ['Non-cancer illness code, self-reported: insomnia'],
 'Iron deficiency anaemia': ['Non-cancer illness code, self-reported: iron deficiency anaemia',
  'Iron deficiency anaemia',
  'Diagnoses - main ICD10: D50 Iron deficiency anaemia'],
 'Irritability': ['Irritability'],
 'Irritable bowel syndrome': ['Non-cancer illness code, self-reported: irritable bowel syndrome',
  'Diagnoses - main ICD10: K58 Irritable bowel syndrome'],
 'Jaundice': ['Diagnoses - main ICD10: R17 Unspecified jaundice'],
 'Joint swelling': ['Non-cancer illness code, self-reported: joint pain'],
 'Lacrimal disorder': ['Disorders of lacrimal system',
  'Diagnoses - main ICD10: H04 Disorders of lachrymal system'],
 'Lacrimation increased': ['Epiphora'],
 'Laryngospasm': ['Non-cancer illness code, self-reported: asthma', 'Asthma'],
 'Left ventricular failure': ['Heart failure'],
 'Liver disorder': ['Diseases of liver'],
 'Lower respiratory tract infection': ['Bronchitis',
  'Non-cancer illness code, self-reported: bronchitis',
  'Non-cancer illness code, self-reported: pneumonia'],
 'Lung neoplasm malignant': ['Cancer code, self-reported: lung cancer'],
 'Lymphoma': ['Hodgkin lymphoma', 'Lymphomas'],
 'Major depression': ['Non-cancer illness code, self-reported: depression',
  'Depression'],
 'Malignant melanoma': ['Cancer code, self-reported: skin cancer',
  'Cancer code, self-reported: malignant melanoma'],
 'Meningitis': ['Non-cancer illness code, self-reported: meningitis'],
 'Meningitis aseptic': ['Non-cancer illness code, self-reported: meningitis'],
 'Migraine': ['Diagnoses - main ICD10: G43 Migraine',
  'Non-cancer illness code, self-reported: migraine',
  'Non-cancer illness code, self-reported: headaches (not migraine)'],
 'Mood swings': ['Mood swings'],
 'Myalgia': ['Myalgia'],
 'Myocardial infarction': ['Diagnoses - main ICD10: I22 Subsequent myocardial infarction',
  'Myocardial infarction',
  'STROKE',
  'Non-cancer illness code, self-reported: stroke',
  'Diagnoses - main ICD10: I21 Acute myocardial infarction'],
 'Myopathy': ['Disorders of muscles'],
 'Nail disorder': ['Diagnoses - main ICD10: L60 Nail disorders',
  'Nail disorders'],
 'Neck pain': ['Cervicalgia'],
 'Neoplasm': ['Neoplasms'],
 'Neoplasm malignant': ['Diagnoses - main ICD10: C80 Malignant neoplasm without specification of site',
  'Neoplasms'],
 'Nervous system disorder': ['Diseases of the nervous system'],
 'Neuropathy peripheral': ['Non-cancer illness code, self-reported: peripheral nerve disorder',
  'Non-cancer illness code, self-reported: peripheral neuropathy'],
 "Non-Hodgkin's lymphoma": [
  'Cancer code, self-reported: non-hodgkins lymphoma'],
 'Oesophageal ulcer': ['Ulcer of oesophagus',
  'Non-cancer illness code, self-reported: peptic ulcer'],
 'Oesophagitis': ['Diagnoses - main ICD10: K20 Oesophagitis'],
 'Osteoarthritis': ['#Arthrosis',
  'Non-cancer illness code, self-reported: arthritis (nos)',
  'Non-cancer illness code, self-reported: osteoarthritis'],
 'Osteomyelitis': ['Non-cancer illness code, self-reported: osteomyelitis',
  'Diagnoses - main ICD10: M86 Osteomyelitis'],
 'Osteonecrosis': ['Non-cancer illness code, self-reported: bone disorder'],
 'Osteopenia': ['Non-cancer illness code, self-reported: osteopenia'],
 'Osteoporosis': ['Non-cancer illness code, self-reported: osteoporosis',
  'Osteoporosis'],
 'Otitis externa': ['Diagnoses - main ICD10: H60 Otitis externa',
  'Otitis externa'],
 'Otitis media': ['Otitis media, unspecified'],
 'Pain': ['Diagnoses - main ICD10: R52 Pain, not elsewhere classified'],
 'Pain in extremity': ['Pain in limb'],
 'Pancreatitis': ['Non-cancer illness code, self-reported: pancreatitis'],
 'Pancreatitis acute': ['Non-cancer illness code, self-reported: pancreatitis',
  'Diagnoses - main ICD10: K85 Acute pancreatitis'],
 'Peliosis hepatis': ['Non-cancer illness code, self-reported: hepatitis'],
 'Peptic ulcer': ['Non-cancer illness code, self-reported: peptic ulcer',
  'Gastroduodenal ulcer'],
 'Peripheral ischaemia': ['Non-cancer illness code, self-reported: peripheral vascular disease'],
 'Peripheral sensory neuropathy': ['Non-cancer illness code, self-reported: peripheral neuropathy'],
 'Peripheral vascular disorder': ['Non-cancer illness code, self-reported: peripheral vascular disease'],
 'Peritonitis': ['Diagnoses - main ICD10: K65 Peritonitis',
  'Non-cancer illness code, self-reported: peritonitis'],
 'Phlebitis': ['Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis'],
 'Phobia': ['Anxiety disorders'],
 'Pleural effusion': ['Diagnoses - main ICD10: J90 Pleural effusion, not elsewhere classified'],
 'Pleurisy': ['Non-cancer illness code, self-reported: pleurisy'],
 'Pneumonia': ['Non-cancer illness code, self-reported: pneumonia'],
 'Pneumothorax': ['Diagnoses - main ICD10: J93 Pneumothorax'],
 'Polymyalgia rheumatica': ['Non-cancer illness code, self-reported: polymyalgia rheumatica'],
 'Polyuria': ['Diagnoses - main ICD10: R35 Polyuria'],
 'Prostatitis': ['Diagnoses - main ICD10: N41 Inflammatory diseases of prostate'],
 'Pruritus': ['Diagnoses - main ICD10: L29 Pruritus'],
 'Psoriasis': ['Diagnoses - main ICD10: L40 Psoriasis',
  'Psoriasis',
  'Non-cancer illness code, self-reported: psoriasis'],
 'Pulmonary embolism': ['Diagnoses - main ICD10: I26 Pulmonary embolism'],
 'Pulmonary hypertension': ['Non-cancer illness code, self-reported: hypertension',
  'Hypertension'],
 'Pyelonephritis': ['Diagnoses - main ICD10: N12 Tubulo-interstitial nephritis, not specified as acute or chronic'],
 'Rash': ['Diagnoses - main ICD10: R21 Rash and other nonspecific skin eruption'],
 'Renal colic': ['Diagnoses - main ICD10: N23 Unspecified renal colic'],
 'Renal failure acute': ['Diagnoses - main ICD10: N17 Acute renal failure'],
 'Renal failure chronic': ['Diagnoses - main ICD10: N18 Chronic renal failure'],
 'Retinal detachment': ['Non-cancer illness code, self-reported: retinal detachment'],
 'Rheumatoid arthritis': ['Rheumatoid arthritis',
  'Rheumatoid Arthritis',
  'Non-cancer illness code, self-reported: rheumatoid arthritis'],
 'Rosacea': ['Non-cancer illness code, self-reported: rosacea'],
 'Schizophrenia': ['Schizophrenia',
  'Non-cancer illness code, self-reported: schizophrenia'],
 'Sciatica': ['Non-cancer illness code, self-reported: sciatica'],
 'Seborrhoeic keratosis': ['Diagnoses - main ICD10: L82 Seborrhoeic keratosis'],
 'Sinus congestion': ['Non-cancer illness code, self-reported: nasal/sinus disorder'],
 'Sinusitis': ['Diagnoses - main ICD10: J32 Chronic sinusitis'],
 'Skin atrophy': ['Diagnoses - main ICD10: L90 Atrophic disorders of skin',
  'Atrophic disorders of skin'],
 'Skin cancer': ['Cancer code, self-reported: skin cancer',
  'Malignant neoplasm of skin',
  'Cancer code, self-reported: non-melanoma skin cancer'],
 'Sleep apnoea syndrome': ['Non-cancer illness code, self-reported: sleep apnoea',
  'Sleep apnoea'],
 'Sleep disorder': ['Diagnoses - main ICD10: G47 Sleep disorders'],
 'Squamous cell carcinoma': ['Cancer code, self-reported: squamous cell carcinoma'],
 'Status epilepticus': ['Non-cancer illness code, self-reported: epilepsy'],
 'Subarachnoid haemorrhage': ['Non-cancer illness code, self-reported: subarachnoid haemorrhage',
  'Diagnoses - main ICD10: I60 Subarachnoid haemorrhage'],
 'Syncope': ['Diagnoses - main ICD10: R55 Syncope and collapse'],
 'Systemic lupus erythematosus': ['Systemic Lupus Erythematosus'],
 'Telangiectasia': ['Non-cancer illness code, self-reported: peripheral vascular disease'],
 'Thrombocytopenia': ['Thrombocytopenia, unspecified'],
 'Tongue disorder': ['Diagnoses - main ICD10: K14 Diseases of tongue'],
 'Tracheobronchitis': ['Bronchitis',
  'Non-cancer illness code, self-reported: bronchitis'],
 'Transient ischaemic attack': ['Non-cancer illness code, self-reported: transient ischaemic attack (tia)'],
 'Upper gastrointestinal haemorrhage': ['GI-bleeding'],
 'Urinary incontinence': ['Diagnoses - main ICD10: R32 Unspecified urinary incontinence'],
 'Urinary retention': ['Diagnoses - main ICD10: R33 Retention of urine'],
 'Urticaria': ['Non-cancer illness code, self-reported: urticaria'],
 'Varicella': ['Non-cancer illness code, self-reported: chickenpox'],
 'Varicose vein': ['Non-cancer illness code, self-reported: varicose veins'],
 'Vertigo': ['Diagnoses - main ICD10: R42 Dizziness and giddiness',
  'Non-cancer illness code, self-reported: vertigo'],
 'Vestibular disorder': ['Diagnoses - main ICD10: H81 Disorders of vestibular function',
  'Non-cancer illness code, self-reported: ear/vestibular disorder'],
 'Viral infection': ['Diagnoses - main ICD10: B34 Viral infection of unspecified site'],
 'Vitreous disorder': ['Diagnoses - main ICD10: H43 Disorders of vitreous body',
  'Disorders of vitreous body'],
 'Xerophthalmia': ['Non-cancer illness code, self-reported: dry eyes']}
